name: Run Benchmarks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    # R
    
    - name: Install libpng-dev
      run: sudo apt-get update && sudo apt-get install -y libpng-dev
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.0'
        use-public-rspm: true
    
    - name: Install pandoc
      uses: r-lib/actions/setup-pandoc@v2
    
    - name: Cache R packages
      uses: actions/cache@v4
      with:
        path: ~/.local/share/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-
    
    - name: Setup renv
      uses: r-lib/actions/setup-renv@v2
      with:
        cache-version: 1

    # Julia
    
    - name: Setup Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: '1.11.6'
    
    - name: Cache Julia pacakges
      uses: julia-actions/cache@v2
    
    - name: Install Julia packages
      run: |
        julia --project=. -e 'using Pkg; Pkg.activate("."); Pkg.instantiate();'

    - name: set julia thread count
      run: echo "JULIA_NUM_THREADS=2" >> $GITHUB_ENV

    # Python
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Create virtual environment
      run: |
        python -m venv .venv
    
    - name: Install Python packages
      run: |
        source .venv/bin/activate
        pip install --upgrade pip
        pip install pandas pyfixest
    
    - name: Make venv available to subsequent steps
      run: |
        source .venv/bin/activate
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH

    - name: set numba parallel flags
      run: echo "NUMBA_NUM_THREADS=2" >> $GITHUB_ENV

    # # Download NYC Taxi data for benchmarks
    # 
    # # Try to download pre-processed data from artifact first
    # - name: Download taxi data artifact
    #   id: download_artifact
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: nyc-taxi-data
    #     path: data/
    #   continue-on-error: true
    # 
    # # If artifact download failed, process the data ourselves  
    # - name: Download and process taxi data
    #   if: steps.download_artifact.outcome == 'failure'
    #   run: Rscript download_taxi.R

    # RUN BENCHMARK
    
    - name: Run benchmarks
      run: |
        source .venv/bin/activate
        Rscript bench.R

    - name: Create figures
      run: |
        source .venv/bin/activate
        Rscript summarize_benchmark.R

    ## Commit results
    
    - name: Commit benchmark results
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update benchmark results [skip ci]"
        file_pattern: "results/*"
